##############################################################################
# Copyright (c) 2016 ZTE Coreporation and others.
# hu.zhijiang@zte.com.cn
# sun.jing22@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
network-config-metadata:
  title: 'zte-virtual2 network config'
  version: '0.1'
  created: 'Tue Apr 11 2017'
  comment: 'all-in-one vm node deploy'
networks:
  - cidr: '10.20.11.0/24'
    gateway: '10.20.11.1'
    ip_ranges:
      - start: '10.20.11.3'
        end: '10.20.11.10'
    name: 'MANAGEMENT'
  - cidr: '10.20.11.0/24'
    gateway: '10.20.11.1'
    ip_ranges:
      - start: '10.20.11.3'
        end: '10.20.11.10'
    name: 'STORAGE'
  - cidr: '172.10.101.0/24'
    gateway: '172.10.101.1'
    ip_ranges:
      - start: '172.10.101.2'
        end: '172.10.101.20'
    name: 'EXTERNAL'
    network_name: 'admin_external'
    mapping: 'physnet1'
  - cidr: '10.20.11.0/24'
    gateway: '10.20.11.1'
    ip_ranges:
      - start: '10.20.11.3'
        end: '10.20.11.10'
    name: 'PUBLICAPI'
  - cidr: '10.20.11.0/24'
    gateway: '10.20.11.1'
    ip_ranges:
      - start: '10.20.11.3'
        end: '10.20.11.10'
    name: 'TENANT'
  - cidr: '100.20.11.0/24'
    gateway: '100.20.11.1'
    ip_ranges:
      - start: '100.20.11.3'
        end: '100.20.11.10'
    name: 'HEARTBEAT'
interfaces:
  - name: 'EXTERNAL'
    interface: 'ens8'
  - name: 'MANAGEMENT'
    interface: 'ens3'
  - name: 'PUBLICAPI'
    interface: 'ens3'
  - name: 'STORAGE'
    interface: 'ens3'
  - name: 'TENANT'
    interface: 'ens3'
  - name: 'HEARTBEAT'
    interface: 'ens9'
internal_vip: '10.20.11.11'
public_vip: '10.20.11.11'
