### POD descriptor file ###

details:
  pod owner: Lab Owner
  contact: email@address.com
  lab: Linux Foundation
  location: Portland, Oregon, USA
  type: {production|development}
  link: http://wiki.opnfv.org/

jumphost:
  name: pod1-jump
  node:
    type: {baremetal|virtual}               # can be virtual or baremetal
    vendor: supermicro
    model: S2600JF
    arch: {x86_64|aarch64}
    cpus: 2
    cpu_cflags: {broadwell|hasewell|etc}    # add values based on CFLAGS in GCC
    cores: 10                               # physical cores, not including hyper-threads
    memory: 32G
  disks:                                    # disk list
    - name: {disk#number}                   # first disk
      disk_capacity: {M|MB|G|GB|T|TB}       # volume
      disk_type: {hdd|ssd|cdrom|tape}       # several disk types possible
      disk_interface: {sata|sas|ssd|nvme}   # several interface types possible
      disk_rotation: {5400|7200|10000|15000} # define rotation speed of disk
    - name: 'disk2'                         # second disk
      disk_capacity: 2048G
      disk_type: hdd
      disk_interface: sas
      disk_rotation: 15000
  os: ubuntu-14.04                          #operation system installed
  remote_para: &remoteparas
    type: {ipmi|amt}                        # hardware manggement tool
    versions:
      - 1.0
      - 2.0
    user: root
    pass: root
  remote_mangement:
    <<: *remoteparas
    address: 10.4.7.3/24
    mac_address: "10:23:45:67:89:AC"
  interfaces:                               # physical interface list
    - nic: {nic#number}                     # first interface
      address: 192.168.100.1                # ip address of nic
      mac_address: "10:23:45:67:89:AC"
      vlan: {native|1-4095}                 # vlan tag, may have multiple tags
    - nic: 'nic2'                           # second interface
      address: 10.20.0.1/24
      mac_address: "10:23:45:67:89:5B"
nodes:
  - name: pod1-node1
    node: &nodeparas                        # for nodes in the same pod may have the same configuration
      type: baremetal
      vendor: supermicro
      model: S2600JF
      arch: x86_64
      cpus: 2
      cpu_cflags: hasewell
      cores: 12
      memory: 128G
    disks: &disks                           # for nodes in the same pod may have the same configuration
      - name: 'disk1'
        disk_capacity: 4906G
        disk_type: hdd
        disk_interface: sata
        disk_rotation: 7200
      - name: 'disk2'
        disk_capacity: 2048G
        disk_type: hdd
        disk_interface: sas
        disk_rotation: 15000
      - name: 'disk3'
        disk_capacity: 600G
        disk_type: ssd
        disk_interface: ssd
        disk_rotation: 15000
    remote_mangement:
      <<: *remoteparas
      address: 10.4.7.7/24
      mac_address: "10:20:22:67:89:A2"
    interfaces:
      - name: 'nic1'
        speed: {1gb|10gb|25gb|40gb}
        features: {dpdk|sriov}
        address: 10.2.4.7/24
        mac_address: "10:23:22:67:89:AC"
        vlan: 201
      - name: 'nic2'
        speed: 1gb
        features: ''
        address: 10.2.4.8/24
        mac_address: "10:23:22:67:89:5B"
        vlan: 202
      - name: 'nic3'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:1b:21:22:f1:b4"
        vlan: 203
      - name: 'nic4'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:1b:21:22:f1:b5"
        vlan: 204
  - name: pod1-node2
    node: *nodeparas
    disks: *disks                           # disks are same as pod1-node1
    remote_mangement:
      <<: *remoteparas
      address: 10.4.7.8/24
      mac_address: "10:20:22:67:88:A3"
    interfaces:
      - name: 'nic1'
        speed: 1gb
        features: ''
        address: 10.2.4.8/24
        mac_address: "10:23:22:67:88:AC"
        vlan: 201
      - name: 'nic2'
        speed: 1gb
        features: ''
        address: 10.2.4.8/24
        mac_address: "10:23:22:67:88:5B"
        vlan: 202
      - name: 'nic3'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:1b:21:22:f8:b4"
        vlan: 203
      - name: 'nic4'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:1b:21:22:f8:b5"

